name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - run: pnpm install

      - uses: lonewolfyx-workflows/npm-public-actions@main
        with:
          package-manager: pnpm

      - run: pnpm run git:release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
